const FETCHED_LOST_PETS = "FETCHED_LOST_PETS";
const POST_LOST_PET = "POST_LOST_PET";
const POST_LOADING = "POST_LOADING";
const FETCHED_MAP_CENTER = "FETCHED_MAP_CENTER";
const FAILED_FETCH = "FAILED_FETCH";
const RESET_FAIL = "RESET_FAIL";
const FETCHED_SIGHTINGS = "FETCHED_SIGHTINGS";
const POSTED_SIGHTING = "POSTED_SIGHTING";

export {
  FETCHED_LOST_PETS,
  POST_LOST_PET,
  POST_LOADING,
  FETCHED_MAP_CENTER,
  FAILED_FETCH,
  RESET_FAIL,
  FETCHED_SIGHTINGS,
  POSTED_SIGHTING
};
